### ISSUE TITLE
forEach, when used in a script, throws "Object #<Object> has no method 'forEach'"

### ISSUE THREAD

**Issue by kurttheviking** [jden/minq#17]
using minq 1, rc 8; ubuntu 14.04; node 0.10.26; npm 1.4.3

### setup

```
var connstr = process.env.DB_CONN_STRING;
var minq = require('minq');

minq.connect(connstr).then(function (db) {
  console.log('connected: ' + connstr);

  return db
    .from('CollectionName')
    .forEach(function (data) {
       console.log(data);
    });
})
.then(function () {
  console.log('done');
});
```

### expected

a log of each item in the collection

```
> {}
> {}
...
```

### actual

```
TypeError: Object #<Object> has no method 'forEach'
    at /home/test.js:23:15
    at Writable.stream._write (/home/node_modules/minq/node_modules/charybdis/index.js:51:14)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Writable.write (_stream_writable.js:183:11)
    at Stream.ondata (stream.js:51:26)
    at Stream.EventEmitter.emit (events.js:95:17)
    at drain (/home/node_modules/minq/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/home/node_modules/minq/node_modules/through/index.js:45:5)
    at Stream.<anonymous> (/home/node_modules/minq/mongodb.js:85:50)
```

### notes

interestingly, if you add a `select(['_id'])` it works fine; however if you add any other element to the select, it fails with the same error

**Comment by jden** [comment]
@kurttheviking I'm going through open minq issues and noticed this. Do you have the original code from `test.js` mentioned in that stack trace? Or do you remember what I'd need to do to come up with a reproduction case?

**Comment by kurttheviking** [comment]
i dont have it handy and this issue is a bit fuzzy in my memory; if i encounter it again ill provide additional repro details with a failing test

**Comment by jden** [comment]
Okay, the specific TypeError is from the version of v8 in node 0.10.26 (v8 3.14.5.9). In newer v8s it's a "x is not a function" message.

I'm going to close this issue.
